---
abstract: 'Yet another JSON-RPC 2.0 psgi application'
author:
  - 'nqounet <mail@nqou.net>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-App-JSONRPC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::App::JSONRPC:
    file: lib/Plack/App/JSONRPC.pm
    version: '0.01'
requires:
  JSON::RPC::Spec: '0'
  Plack: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/nqounet/p5-plack-app-jsonrpc/issues
  homepage: https://github.com/nqounet/p5-plack-app-jsonrpc
  repository: https://github.com/nqounet/p5-plack-app-jsonrpc.git
version: '0.01'
